image: docker:latest

services:
  - docker:dind

stages:
  - Build-Base
  - Build-Git

tags:
  - docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build-base:
  stage: Build-Base
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$GRAV_VERSION" .
    - docker push "$CI_REGISTRY_IMAGE:$GRAV_VERSION"

build-git:
  stage: Build-Git
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$GRAV_VERSION-git" ./git/
    - docker push "$CI_REGISTRY_IMAGE:$GRAV_VERSION-git"