image: docker:latest

services:
  - docker:dind

stages:
  - Base
  - Extra-Git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build-base:
  stage: Base
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}
  except:
    - pushes
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --pull --build-arg "GRAV_VERSION=$GRAV_VERSION" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$CI_REGISTRY_IMAGE:$GRAV_VERSION" .
    - docker push "$CI_REGISTRY_IMAGE:$GRAV_VERSION"
    - docker image ls
    - find . -type f
    - find ${CI_PROJECT_DIR} -type f
    - ls -a /

build-git:
  stage: Extra-Git
  dependencies:
    - build-base
  except:
    - pushes
  script:
    - docker image ls
    - docker build --pull --build-arg "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" -t "$CI_REGISTRY_IMAGE:$GRAV_VERSION-git" ./git/
    - docker push "$CI_REGISTRY_IMAGE:$GRAV_VERSION-git"